name: PHP lint and test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring
    - name: Install dependencies
      run: composer install
    - name: PHP lint
      run: php -l src/
    - name: PHPUnit test
      run: ./test
